import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { parseRgaaJson } from "../src/rgaa-import.js";

// Regenerates src/rgaa-criteria.generated.ts from the official RGAA file.
//   pnpm --filter @accessibility/rules import-rgaa
// The source is pinned to a commit and to the SHA-256 of its content: a moved
// or altered file stops here instead of silently changing the reference.
const COMMIT = "a30ff55e982bab49ab10be673f26603aefe57049";
const SOURCE_URL = `https://raw.githubusercontent.com/DISIC/RGAA/${COMMIT}/v4.1/JSON/criteres.json`;
const SHA256 =
  "ab231f4d763961bc16aa16228f2137f1d97c0769077bab11a4d392dfc13b0816";

const response = await fetch(SOURCE_URL, {
  signal: AbortSignal.timeout(30_000),
});
if (!response.ok) {
  throw new Error(`Could not download ${SOURCE_URL}: HTTP ${response.status}`);
}
const raw = Buffer.from(await response.arrayBuffer());
const actual = createHash("sha256").update(raw).digest("hex");
if (actual !== SHA256) {
  throw new Error(`Unexpected content for ${SOURCE_URL}: sha256 ${actual}`);
}

const data = parseRgaaJson(JSON.parse(raw.toString("utf8")));

const output = `// GENERATED by scripts/import-rgaa.ts: do not edit by hand.
// Source: ${SOURCE_URL}
// Reference: RGAA 4.1 (DINUM), Licence Ouverte 2.0.
// sha256 of the source file: ${SHA256}
import type { RgaaCriterion, RgaaTheme } from "./rgaa-import.js";

export const RGAA_SOURCE = {
  version: "4.1",
  url: ${JSON.stringify(SOURCE_URL)},
  sha256: ${JSON.stringify(SHA256)},
  license: "Licence Ouverte 2.0",
} as const;

export const RGAA_THEMES_DATA: RgaaTheme[] = ${JSON.stringify(data.themes, null, 2)};

export const RGAA_CRITERIA_DATA: RgaaCriterion[] = ${JSON.stringify(data.criteria, null, 2)};
`;
writeFileSync(
  new URL("../src/rgaa-criteria.generated.ts", import.meta.url),
  output,
);
console.log(
  `${data.themes.length} themes, ${data.criteria.length} criteria written`,
);
