// GENERATED by scripts/import-rgaa.ts: do not edit by hand.
// Source: https://raw.githubusercontent.com/DISIC/RGAA/a30ff55e982bab49ab10be673f26603aefe57049/v4.1/JSON/criteres.json
// Reference: RGAA 4.1 (DINUM), Licence Ouverte 2.0.
// sha256 of the source file: ab231f4d763961bc16aa16228f2137f1d97c0769077bab11a4d392dfc13b0816
import type { RgaaCriterion, RgaaTheme } from "./rgaa-import.js";

export const RGAA_SOURCE = {
  version: "4.1",
  url: "https://raw.githubusercontent.com/DISIC/RGAA/a30ff55e982bab49ab10be673f26603aefe57049/v4.1/JSON/criteres.json",
  sha256: "ab231f4d763961bc16aa16228f2137f1d97c0769077bab11a4d392dfc13b0816",
  license: "Licence Ouverte 2.0",
} as const;

export const RGAA_THEMES_DATA: RgaaTheme[] = [
  {
    number: 1,
    title: "Images",
  },
  {
    number: 2,
    title: "Cadres",
  },
  {
    number: 3,
    title: "Couleurs",
  },
  {
    number: 4,
    title: "Multimédia",
  },
  {
    number: 5,
    title: "Tableaux",
  },
  {
    number: 6,
    title: "Liens",
  },
  {
    number: 7,
    title: "Scripts",
  },
  {
    number: 8,
    title: "Éléments obligatoires",
  },
  {
    number: 9,
    title: "Structuration de l'information",
  },
  {
    number: 10,
    title: "Présentation de l'information",
  },
  {
    number: 11,
    title: "Formulaires",
  },
  {
    number: 12,
    title: "Navigation",
  },
  {
    number: 13,
    title: "Consultation",
  },
];

export const RGAA_CRITERIA_DATA: RgaaCriterion[] = [
  {
    id: "1.1",
    theme: 1,
    number: 1,
    title:
      "Chaque image porteuse d'information a-t-elle une alternative textuelle ?",
    testCount: 8,
    wcag: ["1.1.1"],
  },
  {
    id: "1.2",
    theme: 1,
    number: 2,
    title:
      "Chaque image de décoration est-elle correctement ignorée par les technologies d'assistance ?",
    testCount: 6,
    wcag: ["1.1.1", "4.1.2"],
  },
  {
    id: "1.3",
    theme: 1,
    number: 3,
    title:
      "Pour chaque image porteuse d'information ayant une alternative textuelle, cette alternative est-elle pertinente (hors cas particuliers) ?",
    testCount: 9,
    wcag: ["1.1.1", "4.1.2"],
  },
  {
    id: "1.4",
    theme: 1,
    number: 4,
    title:
      "Pour chaque image utilisée comme CAPTCHA ou comme image-test, ayant une alternative textuelle, cette alternative permet-elle d'identifier la nature et la fonction de l'image ?",
    testCount: 7,
    wcag: ["1.1.1"],
  },
  {
    id: "1.5",
    theme: 1,
    number: 5,
    title:
      "Pour chaque image utilisée comme CAPTCHA, une solution d'accès alternatif au contenu ou à la fonction du CAPTCHA est-elle présente ?",
    testCount: 2,
    wcag: ["1.1.1"],
  },
  {
    id: "1.6",
    theme: 1,
    number: 6,
    title:
      "Chaque image porteuse d'information a-t-elle, si nécessaire, une description détaillée ?",
    testCount: 10,
    wcag: ["1.1.1"],
  },
  {
    id: "1.7",
    theme: 1,
    number: 7,
    title:
      "Pour chaque image porteuse d'information ayant une description détaillée, cette description est-elle pertinente ?",
    testCount: 6,
    wcag: ["1.1.1"],
  },
  {
    id: "1.8",
    theme: 1,
    number: 8,
    title:
      "Chaque image texte porteuse d'information, en l'absence d'un mécanisme de remplacement, doit si possible être remplacée par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?",
    testCount: 6,
    wcag: ["1.4.5"],
  },
  {
    id: "1.9",
    theme: 1,
    number: 9,
    title:
      "Chaque légende d'image est-elle, si nécessaire, correctement reliée à l'image correspondante ?",
    testCount: 5,
    wcag: ["1.1.1", "4.1.2"],
  },
  {
    id: "2.1",
    theme: 2,
    number: 1,
    title: "Chaque cadre a-t-il un titre de cadre ?",
    testCount: 1,
    wcag: ["4.1.2"],
  },
  {
    id: "2.2",
    theme: 2,
    number: 2,
    title:
      "Pour chaque cadre ayant un titre de cadre, ce titre de cadre est-il pertinent ?",
    testCount: 1,
    wcag: ["4.1.2"],
  },
  {
    id: "3.1",
    theme: 3,
    number: 1,
    title:
      "Dans chaque page web, l'information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?",
    testCount: 6,
    wcag: ["1.3.1", "1.4.1"],
  },
  {
    id: "3.2",
    theme: 3,
    number: 2,
    title:
      "Dans chaque page web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?",
    testCount: 5,
    wcag: ["1.4.3"],
  },
  {
    id: "3.3",
    theme: 3,
    number: 3,
    title:
      "Dans chaque page web, les couleurs utilisées dans les composants d'interface ou les éléments graphiques porteurs d'informations sont-elles suffisamment contrastées (hors cas particuliers) ?",
    testCount: 4,
    wcag: ["1.4.11"],
  },
  {
    id: "4.1",
    theme: 4,
    number: 1,
    title:
      "Chaque média temporel pré-enregistré a-t-il, si nécessaire, une transcription textuelle ou une audiodescription (hors cas particuliers) ?",
    testCount: 3,
    wcag: ["1.2.1", "1.2.3"],
  },
  {
    id: "4.2",
    theme: 4,
    number: 2,
    title:
      "Pour chaque média temporel pré-enregistré ayant une transcription textuelle ou une audiodescription synchronisée, celles-ci sont-elles pertinentes (hors cas particuliers) ?",
    testCount: 3,
    wcag: ["1.2.1", "1.2.3"],
  },
  {
    id: "4.3",
    theme: 4,
    number: 3,
    title:
      "Chaque média temporel synchronisé pré-enregistré a-t-il, si nécessaire, des sous-titres synchronisés (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["1.2.2"],
  },
  {
    id: "4.4",
    theme: 4,
    number: 4,
    title:
      "Pour chaque média temporel synchronisé pré-enregistré ayant des sous-titres synchronisés, ces sous-titres sont-ils pertinents ?",
    testCount: 1,
    wcag: ["1.2.2"],
  },
  {
    id: "4.5",
    theme: 4,
    number: 5,
    title:
      "Chaque média temporel pré-enregistré a-t-il, si nécessaire, une audiodescription synchronisée (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["1.2.5"],
  },
  {
    id: "4.6",
    theme: 4,
    number: 6,
    title:
      "Pour chaque média temporel pré-enregistré ayant une audiodescription synchronisée, celle-ci est-elle pertinente ?",
    testCount: 2,
    wcag: ["1.2.5"],
  },
  {
    id: "4.7",
    theme: 4,
    number: 7,
    title:
      "Chaque média temporel est-il clairement identifiable (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["1.1.1"],
  },
  {
    id: "4.8",
    theme: 4,
    number: 8,
    title:
      "Chaque média non temporel a-t-il, si nécessaire, une alternative (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["1.1.1"],
  },
  {
    id: "4.9",
    theme: 4,
    number: 9,
    title:
      "Pour chaque média non temporel ayant une alternative, cette alternative est-elle pertinente ?",
    testCount: 1,
    wcag: ["1.1.1"],
  },
  {
    id: "4.10",
    theme: 4,
    number: 10,
    title:
      "Chaque son déclenché automatiquement est-il contrôlable par l'utilisateur ?",
    testCount: 1,
    wcag: ["1.4.2"],
  },
  {
    id: "4.11",
    theme: 4,
    number: 11,
    title:
      "La consultation de chaque média temporel est-elle, si nécessaire, contrôlable par le clavier et tout dispositif de pointage ?",
    testCount: 3,
    wcag: ["2.1.1", "2.1.2"],
  },
  {
    id: "4.12",
    theme: 4,
    number: 12,
    title:
      "La consultation de chaque média non temporel est-elle contrôlable par le clavier et tout dispositif de pointage ?",
    testCount: 2,
    wcag: ["2.1.1", "2.1.2"],
  },
  {
    id: "4.13",
    theme: 4,
    number: 13,
    title:
      "Chaque média temporel et non temporel est-il compatible avec les technologies d'assistance (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["4.1.2"],
  },
  {
    id: "5.1",
    theme: 5,
    number: 1,
    title: "Chaque tableau de données complexe a-t-il un résumé ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "5.2",
    theme: 5,
    number: 2,
    title:
      "Pour chaque tableau de données complexe ayant un résumé, celui-ci est-il pertinent ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "5.3",
    theme: 5,
    number: 3,
    title:
      "Pour chaque tableau de mise en forme, le contenu linéarisé reste-t-il compréhensible ?",
    testCount: 1,
    wcag: ["1.3.2", "4.1.2"],
  },
  {
    id: "5.4",
    theme: 5,
    number: 4,
    title:
      "Pour chaque tableau de données ayant un titre, le titre est-il correctement associé au tableau de données ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "5.5",
    theme: 5,
    number: 5,
    title:
      "Pour chaque tableau de données ayant un titre, celui-ci est-il pertinent ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "5.6",
    theme: 5,
    number: 6,
    title:
      "Pour chaque tableau de données, chaque en-tête de colonne et chaque en-tête de ligne sont-ils correctement déclarés ?",
    testCount: 4,
    wcag: ["1.3.1"],
  },
  {
    id: "5.7",
    theme: 5,
    number: 7,
    title:
      "Pour chaque tableau de données, la technique appropriée permettant d'associer chaque cellule avec ses en-têtes est-elle utilisée (hors cas particuliers) ?",
    testCount: 5,
    wcag: ["1.3.1"],
  },
  {
    id: "5.8",
    theme: 5,
    number: 8,
    title:
      "Chaque tableau de mise en forme ne doit pas utiliser d'éléments propres aux tableaux de données. Cette règle est-elle respectée ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "6.1",
    theme: 6,
    number: 1,
    title: "Chaque lien est-il explicite (hors cas particuliers) ?",
    testCount: 5,
    wcag: ["1.1.1", "2.4.4", "2.5.3"],
  },
  {
    id: "6.2",
    theme: 6,
    number: 2,
    title: "Dans chaque page web, chaque lien a-t-il un intitulé ?",
    testCount: 1,
    wcag: ["1.1.1", "2.4.4"],
  },
  {
    id: "7.1",
    theme: 7,
    number: 1,
    title:
      "Chaque script est-il, si nécessaire, compatible avec les technologies d'assistance ?",
    testCount: 3,
    wcag: ["2.5.3", "4.1.2"],
  },
  {
    id: "7.2",
    theme: 7,
    number: 2,
    title:
      "Pour chaque script ayant une alternative, cette alternative est-elle pertinente ?",
    testCount: 2,
    wcag: ["1.1.1", "4.1.2"],
  },
  {
    id: "7.3",
    theme: 7,
    number: 3,
    title:
      "Chaque script est-il contrôlable par le clavier et par tout dispositif de pointage (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["1.3.1", "2.1.1", "2.4.7"],
  },
  {
    id: "7.4",
    theme: 7,
    number: 4,
    title:
      "Pour chaque script qui initie un changement de contexte, l'utilisateur est-il averti ou en a-t-il le contrôle ?",
    testCount: 1,
    wcag: ["3.2.1", "3.2.2"],
  },
  {
    id: "7.5",
    theme: 7,
    number: 5,
    title:
      "Dans chaque page web, les messages de statut sont-ils correctement restitués par les technologies d'assistance ?",
    testCount: 3,
    wcag: ["4.1.3"],
  },
  {
    id: "8.1",
    theme: 8,
    number: 1,
    title: "Chaque page web est-elle définie par un type de document ?",
    testCount: 3,
    wcag: ["4.1.1"],
  },
  {
    id: "8.2",
    theme: 8,
    number: 2,
    title:
      "Pour chaque page web, le code source généré est-il valide selon le type de document spécifié ?",
    testCount: 1,
    wcag: ["4.1.1", "4.1.2"],
  },
  {
    id: "8.3",
    theme: 8,
    number: 3,
    title: "Dans chaque page web, la langue par défaut est-elle présente ?",
    testCount: 1,
    wcag: ["3.1.1"],
  },
  {
    id: "8.4",
    theme: 8,
    number: 4,
    title:
      "Pour chaque page web ayant une langue par défaut, le code de langue est-il pertinent ?",
    testCount: 1,
    wcag: ["3.1.1"],
  },
  {
    id: "8.5",
    theme: 8,
    number: 5,
    title: "Chaque page web a-t-elle un titre de page ?",
    testCount: 1,
    wcag: ["2.4.2"],
  },
  {
    id: "8.6",
    theme: 8,
    number: 6,
    title:
      "Pour chaque page web ayant un titre de page, ce titre est-il pertinent ?",
    testCount: 1,
    wcag: ["2.4.2"],
  },
  {
    id: "8.7",
    theme: 8,
    number: 7,
    title:
      "Dans chaque page web, chaque changement de langue est-il indiqué dans le code source (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["3.1.2"],
  },
  {
    id: "8.8",
    theme: 8,
    number: 8,
    title:
      "Dans chaque page web, le code de langue de chaque changement de langue est-il valide et pertinent ?",
    testCount: 1,
    wcag: ["3.1.2"],
  },
  {
    id: "8.9",
    theme: 8,
    number: 9,
    title:
      "Dans chaque page web, les balises ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "8.10",
    theme: 8,
    number: 10,
    title:
      "Dans chaque page web, les changements du sens de lecture sont-ils signalés ?",
    testCount: 2,
    wcag: ["1.3.2"],
  },
  {
    id: "9.1",
    theme: 9,
    number: 1,
    title:
      "Dans chaque page web, l'information est-elle structurée par l'utilisation appropriée de titres ?",
    testCount: 3,
    wcag: ["1.3.1", "2.4.1", "2.4.6", "4.1.2"],
  },
  {
    id: "9.2",
    theme: 9,
    number: 2,
    title:
      "Dans chaque page web, la structure du document est-elle cohérente (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["1.3.1"],
  },
  {
    id: "9.3",
    theme: 9,
    number: 3,
    title:
      "Dans chaque page web, chaque liste est-elle correctement structurée ?",
    testCount: 3,
    wcag: ["1.3.1"],
  },
  {
    id: "9.4",
    theme: 9,
    number: 4,
    title:
      "Dans chaque page web, chaque citation est-elle correctement indiquée ?",
    testCount: 2,
    wcag: ["1.3.1"],
  },
  {
    id: "10.1",
    theme: 10,
    number: 1,
    title:
      "Dans le site web, des feuilles de styles sont-elles utilisées pour contrôler la présentation de l'information ?",
    testCount: 3,
    wcag: ["1.3.1", "1.3.2"],
  },
  {
    id: "10.2",
    theme: 10,
    number: 2,
    title:
      "Dans chaque page web, le contenu visible porteur d’information reste-t-il présent lorsque les feuilles de styles sont désactivées ?",
    testCount: 1,
    wcag: ["1.1.1", "1.3.1"],
  },
  {
    id: "10.3",
    theme: 10,
    number: 3,
    title:
      "Dans chaque page web, l'information reste-t-elle compréhensible lorsque les feuilles de styles sont désactivées ?",
    testCount: 1,
    wcag: ["1.3.2", "2.4.3"],
  },
  {
    id: "10.4",
    theme: 10,
    number: 4,
    title:
      "Dans chaque page web, le texte reste-t-il lisible lorsque la taille des caractères est augmentée jusqu'à 200%, au moins (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["1.4.4"],
  },
  {
    id: "10.5",
    theme: 10,
    number: 5,
    title:
      "Dans chaque page web, les déclarations CSS de couleurs de fond d'élément et de police sont-elles correctement utilisées ?",
    testCount: 3,
    wcag: ["1.4.3"],
  },
  {
    id: "10.6",
    theme: 10,
    number: 6,
    title:
      "Dans chaque page web, chaque lien dont la nature n'est pas évidente est-il visible par rapport au texte environnant ?",
    testCount: 1,
    wcag: ["1.4.1"],
  },
  {
    id: "10.7",
    theme: 10,
    number: 7,
    title:
      "Dans chaque page web, pour chaque élément recevant le focus, la prise de focus est-elle visible ?",
    testCount: 1,
    wcag: ["1.4.1", "2.4.7"],
  },
  {
    id: "10.8",
    theme: 10,
    number: 8,
    title:
      "Pour chaque page web, les contenus cachés ont-ils vocation à être ignorés par les technologies d'assistance ?",
    testCount: 1,
    wcag: ["1.3.2", "4.1.2"],
  },
  {
    id: "10.9",
    theme: 10,
    number: 9,
    title:
      "Dans chaque page web, l'information ne doit pas être donnée uniquement par la forme, taille ou position. Cette règle est-elle respectée ?",
    testCount: 4,
    wcag: ["1.3.3", "1.4.1"],
  },
  {
    id: "10.10",
    theme: 10,
    number: 10,
    title:
      "Dans chaque page web, l'information ne doit pas être donnée par la forme, taille ou position uniquement. Cette règle est-elle implémentée de façon pertinente ?",
    testCount: 4,
    wcag: ["1.3.3", "1.4.1"],
  },
  {
    id: "10.11",
    theme: 10,
    number: 11,
    title:
      "Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["1.4.10"],
  },
  {
    id: "10.12",
    theme: 10,
    number: 12,
    title:
      "Dans chaque page web, les propriétés d'espacement du texte peuvent-elles être redéfinies par l'utilisateur sans perte de contenu ou de fonctionnalité (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["1.4.12"],
  },
  {
    id: "10.13",
    theme: 10,
    number: 13,
    title:
      "Dans chaque page web, les contenus additionnels apparaissant à la prise de focus ou au survol d'un composant d'interface sont-ils contrôlables par l'utilisateur (hors cas particuliers) ?",
    testCount: 3,
    wcag: ["1.4.13"],
  },
  {
    id: "10.14",
    theme: 10,
    number: 14,
    title:
      "Dans chaque page web, les contenus additionnels apparaissant via les styles CSS uniquement peuvent-ils être rendus visibles au clavier et par tout dispositif de pointage ?",
    testCount: 2,
    wcag: ["2.1.1"],
  },
  {
    id: "11.1",
    theme: 11,
    number: 1,
    title: "Chaque champ de formulaire a-t-il une étiquette ?",
    testCount: 3,
    wcag: ["1.3.1", "2.4.6", "3.3.2", "4.1.2"],
  },
  {
    id: "11.2",
    theme: 11,
    number: 2,
    title:
      "Chaque étiquette associée à un champ de formulaire est-elle pertinente (hors cas particuliers) ?",
    testCount: 6,
    wcag: ["2.4.6", "2.5.3", "3.3.2"],
  },
  {
    id: "11.3",
    theme: 11,
    number: 3,
    title:
      "Dans chaque formulaire, chaque étiquette associée à un champ de formulaire ayant la même fonction et répétée plusieurs fois dans une même page ou dans un ensemble de pages est-elle cohérente ?",
    testCount: 2,
    wcag: ["3.2.4"],
  },
  {
    id: "11.4",
    theme: 11,
    number: 4,
    title:
      "Dans chaque formulaire, chaque étiquette de champ et son champ associé sont-ils accolés (hors cas particuliers) ?",
    testCount: 3,
    wcag: ["3.3.2"],
  },
  {
    id: "11.5",
    theme: 11,
    number: 5,
    title:
      "Dans chaque formulaire, les champs de même nature sont-ils regroupés, si nécessaire ?",
    testCount: 1,
    wcag: ["1.3.1", "3.3.2"],
  },
  {
    id: "11.6",
    theme: 11,
    number: 6,
    title:
      "Dans chaque formulaire, chaque regroupement de champs de même nature a-t-il une légende ?",
    testCount: 1,
    wcag: ["1.3.1", "3.3.2"],
  },
  {
    id: "11.7",
    theme: 11,
    number: 7,
    title:
      "Dans chaque formulaire, chaque légende associée à un regroupement de champs de même nature est-elle pertinente ?",
    testCount: 1,
    wcag: ["1.3.1", "3.3.2"],
  },
  {
    id: "11.8",
    theme: 11,
    number: 8,
    title:
      "Dans chaque formulaire, les items de même nature d'une liste de choix sont-ils regroupés de manière pertinente ?",
    testCount: 3,
    wcag: ["1.3.1"],
  },
  {
    id: "11.9",
    theme: 11,
    number: 9,
    title:
      "Dans chaque formulaire, l'intitulé de chaque bouton est-il pertinent (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["2.5.3", "4.1.2"],
  },
  {
    id: "11.10",
    theme: 11,
    number: 10,
    title:
      "Dans chaque formulaire, le contrôle de saisie est-il utilisé de manière pertinente (hors cas particuliers) ?",
    testCount: 7,
    wcag: ["3.3.1", "3.3.2"],
  },
  {
    id: "11.11",
    theme: 11,
    number: 11,
    title:
      "Dans chaque formulaire, le contrôle de saisie est-il accompagné, si nécessaire, de suggestions facilitant la correction des erreurs de saisie ?",
    testCount: 2,
    wcag: ["3.3.3"],
  },
  {
    id: "11.12",
    theme: 11,
    number: 12,
    title:
      "Pour chaque formulaire qui modifie ou supprime des données, ou qui transmet des réponses à un test ou à un examen, ou dont la validation a des conséquences financières ou juridiques, les données saisies peuvent-elles être modifiées, mises à jour ou récupérées par l'utilisateur ?",
    testCount: 2,
    wcag: ["3.3.4"],
  },
  {
    id: "11.13",
    theme: 11,
    number: 13,
    title:
      "La finalité d'un champ de saisie peut-elle être déduite pour faciliter le remplissage automatique des champs avec les données de l'utilisateur ?",
    testCount: 1,
    wcag: ["1.3.5"],
  },
  {
    id: "12.1",
    theme: 12,
    number: 1,
    title:
      "Chaque ensemble de pages dispose-t-il de deux systèmes de navigation différents, au moins (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["2.4.5"],
  },
  {
    id: "12.2",
    theme: 12,
    number: 2,
    title:
      "Dans chaque ensemble de pages, le menu et les barres de navigation sont-ils toujours à la même place (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["3.2.3"],
  },
  {
    id: "12.3",
    theme: 12,
    number: 3,
    title: "La page « plan du site » est-elle pertinente ?",
    testCount: 3,
    wcag: ["2.4.5"],
  },
  {
    id: "12.4",
    theme: 12,
    number: 4,
    title:
      "Dans chaque ensemble de pages, la page « plan du site » est-elle atteignable de manière identique ?",
    testCount: 3,
    wcag: ["2.4.5", "3.2.3"],
  },
  {
    id: "12.5",
    theme: 12,
    number: 5,
    title:
      "Dans chaque ensemble de pages, le moteur de recherche est-il atteignable de manière identique ?",
    testCount: 3,
    wcag: ["3.2.3"],
  },
  {
    id: "12.6",
    theme: 12,
    number: 6,
    title:
      "Les zones de regroupement de contenus présentes dans plusieurs pages web (zones d'en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche) peuvent-elles être atteintes ou évitées ?",
    testCount: 1,
    wcag: ["1.3.1", "2.4.1", "4.1.2"],
  },
  {
    id: "12.7",
    theme: 12,
    number: 7,
    title:
      "Dans chaque page web, un lien d'évitement ou d'accès rapide à la zone de contenu principal est-il présent (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["2.4.1", "2.4.3", "3.2.3"],
  },
  {
    id: "12.8",
    theme: 12,
    number: 8,
    title: "Dans chaque page web, l'ordre de tabulation est-il cohérent ?",
    testCount: 2,
    wcag: ["2.4.3"],
  },
  {
    id: "12.9",
    theme: 12,
    number: 9,
    title:
      "Dans chaque page web, la navigation ne doit pas contenir de piège au clavier. Cette règle est-elle respectée ?",
    testCount: 1,
    wcag: ["2.1.1", "2.1.2"],
  },
  {
    id: "12.10",
    theme: 12,
    number: 10,
    title:
      "Dans chaque page web, les raccourcis clavier n'utilisant qu'une seule touche (lettre minuscule ou majuscule, ponctuation, chiffre ou symbole) sont-ils contrôlables par l’utilisateur ?",
    testCount: 1,
    wcag: ["2.1.4"],
  },
  {
    id: "12.11",
    theme: 12,
    number: 11,
    title:
      "Dans chaque page web, les contenus additionnels apparaissant au survol, à la prise de focus ou à l'activation d'un composant d'interface sont-ils si nécessaire atteignables au clavier ?",
    testCount: 1,
    wcag: ["2.1.1"],
  },
  {
    id: "13.1",
    theme: 13,
    number: 1,
    title:
      "Pour chaque page web, l'utilisateur a-t-il le contrôle de chaque limite de temps modifiant le contenu (hors cas particuliers) ?",
    testCount: 4,
    wcag: ["2.2.1", "2.2.2"],
  },
  {
    id: "13.2",
    theme: 13,
    number: 2,
    title:
      "Dans chaque page web, l'ouverture d'une nouvelle fenêtre ne doit pas être déclenchée sans action de l'utilisateur. Cette règle est-elle respectée ?",
    testCount: 1,
    wcag: ["3.2.1"],
  },
  {
    id: "13.3",
    theme: 13,
    number: 3,
    title:
      "Dans chaque page web, chaque document bureautique en téléchargement possède-t-il, si nécessaire, une version accessible (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["1.1.1", "1.3.1", "1.3.2", "2.4.1", "2.4.3", "3.1.1", "4.1.2"],
  },
  {
    id: "13.4",
    theme: 13,
    number: 4,
    title:
      "Pour chaque document bureautique ayant une version accessible, cette version offre-t-elle la même information ?",
    testCount: 1,
    wcag: ["1.1.1", "1.3.1", "1.3.2", "2.4.1", "2.4.3", "3.1.1", "4.1.2"],
  },
  {
    id: "13.5",
    theme: 13,
    number: 5,
    title:
      "Dans chaque page web, chaque contenu cryptique (art ASCII, émoticône, syntaxe cryptique) a-t-il une alternative ?",
    testCount: 1,
    wcag: ["1.1.1"],
  },
  {
    id: "13.6",
    theme: 13,
    number: 6,
    title:
      "Dans chaque page web, pour chaque contenu cryptique (art ASCII, émoticône, syntaxe cryptique) ayant une alternative, cette alternative est-elle pertinente ?",
    testCount: 1,
    wcag: ["1.1.1"],
  },
  {
    id: "13.7",
    theme: 13,
    number: 7,
    title:
      "Dans chaque page web, les changements brusques de luminosité ou les effets de flash sont-ils correctement utilisés ?",
    testCount: 3,
    wcag: ["2.3.1"],
  },
  {
    id: "13.8",
    theme: 13,
    number: 8,
    title:
      "Dans chaque page web, chaque contenu en mouvement ou clignotant est-il contrôlable par l'utilisateur ?",
    testCount: 2,
    wcag: ["2.2.1", "2.2.2"],
  },
  {
    id: "13.9",
    theme: 13,
    number: 9,
    title:
      "Dans chaque page web, le contenu proposé est-il consultable quelle que soit l'orientation de l'écran (portrait ou paysage) (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["1.3.4"],
  },
  {
    id: "13.10",
    theme: 13,
    number: 10,
    title:
      "Dans chaque page web, les fonctionnalités utilisables ou disponibles au moyen d'un geste complexe peuvent-elles être également disponibles au moyen d'un geste simple (hors cas particuliers) ?",
    testCount: 2,
    wcag: ["2.5.1"],
  },
  {
    id: "13.11",
    theme: 13,
    number: 11,
    title:
      "Dans chaque page web, les actions déclenchées au moyen d'un dispositif de pointage sur un point unique de l'écran peuvent-elles faire l'objet d'une annulation (hors cas particuliers) ?",
    testCount: 1,
    wcag: ["2.5.2"],
  },
  {
    id: "13.12",
    theme: 13,
    number: 12,
    title:
      "Dans chaque page web, les fonctionnalités qui impliquent un mouvement de l'appareil ou vers l'appareil peuvent-elles être satisfaites de manière alternative (hors cas particuliers) ?",
    testCount: 3,
    wcag: ["2.5.4"],
  },
];
